# 🐼 Pandas Basics — Practice Notebook

In this notebook, we will learn the **basic operations of Pandas** step-by-step using a simple sample dataset.

**Topics covered:**
1. Creating Series and DataFrame
2. Reading/Writing CSV files
3. Exploring data (head, tail, info, describe)
4. Selection & Indexing (loc, iloc)
5. Filtering rows
6. Adding/Removing columns
7. Sorting
8. Handling missing values
9. GroupBy basics
10. Apply function
11. Basic statistics

## 1️⃣ Pandas Series

In [1]:
import pandas as pd
import numpy as np

# A Series is like a 1-dimensional array with labels
marks = pd.Series([85, 92, 78, 90, 88], index=["Ali", "Sara", "Bilal", "Ayesha", "Usman"])
marks

Ali       85
Sara      92
Bilal     78
Ayesha    90
Usman     88
dtype: int64

In [2]:
# Basic operations on a Series
print("Max:", marks.max())
print("Min:", marks.min())
print("Mean:", marks.mean())
print("Value at Sara:", marks["Sara"])

Max: 92
Min: 78
Mean: 86.6
Value at Sara: 92

## 2️⃣ Creating a DataFrame

A DataFrame is the most important structure in Pandas — it is a table (rows x columns).

In [3]:
data = {
    "Name": ["Ali", "Sara", "Bilal", "Ayesha", "Usman"],
    "Age": [23, 21, 25, 22, 24],
    "City": ["Rawalpindi", "Lahore", "Karachi", "Islamabad", "Multan"],
    "Marks": [85, 92, 78, 90, 88]
}

df = pd.DataFrame(data)
df

     Name  Age        City  Marks
0     Ali   23  Rawalpindi     85
1    Sara   21      Lahore     92
2   Bilal   25     Karachi     78
3  Ayesha   22   Islamabad     90
4   Usman   24      Multan     88

## 3️⃣ Reading / Writing CSV Files

In [4]:
# Save DataFrame to a CSV file
df.to_csv("students.csv", index=False)

# Load it back from the CSV file
df = pd.read_csv("students.csv")
df

     Name  Age        City  Marks
0     Ali   23  Rawalpindi     85
1    Sara   21      Lahore     92
2   Bilal   25     Karachi     78
3  Ayesha   22   Islamabad     90
4   Usman   24      Multan     88

## 4️⃣ Exploring the Data

In [5]:
df.head()   # first 5 rows

     Name  Age        City  Marks
0     Ali   23  Rawalpindi     85
1    Sara   21      Lahore     92
2   Bilal   25     Karachi     78
3  Ayesha   22   Islamabad     90
4   Usman   24      Multan     88

In [6]:
df.tail(2)   # last 2 rows

     Name  Age       City  Marks
3  Ayesha   22  Islamabad     90
4   Usman   24     Multan     88

In [7]:
df.shape   # (rows, columns)

(5, 4)

In [8]:
df.info()   # columns, data types, non-null counts

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   City    5 non-null      str
 3   Marks   5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [9]:
df.describe()   # statistics for numeric columns

             Age      Marks
count   5.000000   5.000000
mean   23.000000  86.600000
std     1.581139   5.458938
min    21.000000  78.000000
25%    22.000000  85.000000
50%    23.000000  88.000000
75%    24.000000  90.000000
max    25.000000  92.000000

In [10]:
df.columns   # column names

Index(['Name', 'Age', 'City', 'Marks'], dtype='str')

## 5️⃣ Selection & Indexing

`loc` = label-based selection
`iloc` = position/index-based selection

In [11]:
# Selecting a single column
df["Name"]

0       Ali
1      Sara
2     Bilal
3    Ayesha
4     Usman
Name: Name, dtype: str

In [12]:
# Selecting multiple columns
df[["Name", "Marks"]]

     Name  Marks
0     Ali     85
1    Sara     92
2   Bilal     78
3  Ayesha     90
4   Usman     88

In [13]:
# loc -> label based (row label, column label)
df.loc[0]          # first row

Name            Ali
Age              23
City     Rawalpindi
Marks            85
Name: 0, dtype: object

In [14]:
df.loc[0, "Name"]   # specific value

'Ali'

In [15]:
# iloc -> position based
df.iloc[1]          # 2nd row (index 1)

Name       Sara
Age          21
City     Lahore
Marks        92
Name: 1, dtype: object

In [16]:
df.iloc[0:3, 0:2]   # first 3 rows, first 2 columns

    Name  Age
0    Ali   23
1   Sara   21
2  Bilal   25

## 6️⃣ Filtering Rows (Conditions)

In [17]:
# Students who scored above 85
df[df["Marks"] > 85]

     Name  Age       City  Marks
1    Sara   21     Lahore     92
3  Ayesha   22  Islamabad     90
4   Usman   24     Multan     88

In [18]:
# Multiple conditions (AND -> &, OR -> |)
df[(df["Marks"] > 80) & (df["Age"] < 24)]

     Name  Age        City  Marks
0     Ali   23  Rawalpindi     85
1    Sara   21      Lahore     92
3  Ayesha   22   Islamabad     90

In [19]:
# Data for a specific city
df[df["City"] == "Lahore"]

   Name  Age    City  Marks
1  Sara   21  Lahore     92

## 7️⃣ Adding/Removing Columns

In [20]:
# Adding a new column
df["Grade"] = ["A", "A+", "B+", "A", "A-"]
df

     Name  Age        City  Marks Grade
0     Ali   23  Rawalpindi     85     A
1    Sara   21      Lahore     92    A+
2   Bilal   25     Karachi     78    B+
3  Ayesha   22   Islamabad     90     A
4   Usman   24      Multan     88    A-

In [21]:
# Creating a new column based on a calculation from an existing column
df["Marks_Percentage"] = (df["Marks"] / 100) * 100
df

     Name  Age        City  Marks Grade  Marks_Percentage
0     Ali   23  Rawalpindi     85     A              85.0
1    Sara   21      Lahore     92    A+              92.0
2   Bilal   25     Karachi     78    B+              78.0
3  Ayesha   22   Islamabad     90     A              90.0
4   Usman   24      Multan     88    A-              88.0

In [22]:
# Removing a column
df = df.drop(columns=["Marks_Percentage"])
df

     Name  Age        City  Marks Grade
0     Ali   23  Rawalpindi     85     A
1    Sara   21      Lahore     92    A+
2   Bilal   25     Karachi     78    B+
3  Ayesha   22   Islamabad     90     A
4   Usman   24      Multan     88    A-

## 8️⃣ Sorting

In [23]:
# Sort by Marks in descending order
df.sort_values(by="Marks", ascending=False)

     Name  Age        City  Marks Grade
1    Sara   21      Lahore     92    A+
3  Ayesha   22   Islamabad     90     A
4   Usman   24      Multan     88    A-
0     Ali   23  Rawalpindi     85     A
2   Bilal   25     Karachi     78    B+

In [24]:
# Sort by multiple columns
df.sort_values(by=["City", "Age"])

     Name  Age        City  Marks Grade
3  Ayesha   22   Islamabad     90     A
2   Bilal   25     Karachi     78    B+
1    Sara   21      Lahore     92    A+
4   Usman   24      Multan     88    A-
0     Ali   23  Rawalpindi     85     A

## 9️⃣ Handling Missing Values

In [25]:
# Example dataset with a missing value
df2 = df.copy()
df2.loc[2, "Marks"] = np.nan
df2

     Name  Age        City  Marks Grade
0     Ali   23  Rawalpindi   85.0     A
1    Sara   21      Lahore   92.0    A+
2   Bilal   25     Karachi    NaN    B+
3  Ayesha   22   Islamabad   90.0     A
4   Usman   24      Multan   88.0    A-

In [26]:
# Checking for missing values
df2.isnull().sum()

Name     0
Age      0
City     0
Marks    1
Grade    0
dtype: int64

In [27]:
# Filling a missing value (with the mean)
df2["Marks"] = df2["Marks"].fillna(df2["Marks"].mean())
df2

     Name  Age        City  Marks Grade
0     Ali   23  Rawalpindi  85.00     A
1    Sara   21      Lahore  92.00    A+
2   Bilal   25     Karachi  88.75    B+
3  Ayesha   22   Islamabad  90.00     A
4   Usman   24      Multan  88.00    A-

In [28]:
# Dropping rows with missing values (if needed)
# df2.dropna()

## 🔟 GroupBy Basics

In [29]:
# Average marks by city
df.groupby("City")["Marks"].mean()

City
Islamabad     90.0
Karachi       78.0
Lahore        92.0
Multan        88.0
Rawalpindi    85.0
Name: Marks, dtype: float64

In [30]:
# Multiple aggregations
df.groupby("City")["Marks"].agg(["mean", "max", "min"])

            mean  max  min
City
Islamabad   90.0   90   90
Karachi     78.0   78   78
Lahore      92.0   92   92
Multan      88.0   88   88
Rawalpindi  85.0   85   85

## 1️⃣1️⃣ Apply Function

In [31]:
# Applying a custom function to each row
def pass_fail(marks):
    return "Pass" if marks >= 80 else "Fail"

df["Result"] = df["Marks"].apply(pass_fail)
df

     Name  Age        City  Marks Grade Result
0     Ali   23  Rawalpindi     85     A   Pass
1    Sara   21      Lahore     92    A+   Pass
2   Bilal   25     Karachi     78    B+   Fail
3  Ayesha   22   Islamabad     90     A   Pass
4   Usman   24      Multan     88    A-   Pass

## 1️⃣2️⃣ Basic Statistics

In [32]:
print("Average Marks:", df["Marks"].mean())
print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())
print("Total Students:", df["Name"].count())
print("Standard Deviation:", df["Marks"].std())

Average Marks: 86.6
Highest Marks: 92
Lowest Marks: 78
Total Students: 5
Standard Deviation: 5.458937625582473

## 🎯 Practice Exercises

1. Create a new column `Age_Group` that shows "Young" (age<23) or "Adult" (age>=23).
2. Retrieve Ayesha's row using only `loc`.
3. Sort the data by Marks in ascending order.
4. Find the average `Age` for each `Grade` group (groupby).
5. Add a new row to `df` using `.loc` or `pd.concat()`.

Happy Practicing! 🐼